package ptolemy.myactors.MaximumEntropy;

public class Auxiliar {

	
	//666,666 - de onde vai começar depois que clica em play 1111 111 - 
	// (111,111) - 1 quart.
	// (999,111) - 2 quart
	// (111,777) - 3 quart
	// (999,777) - 4 quart
	
	//linha 134 - property name='_location' class='ptolemy.kernel.util.Location' value='{222.0, 222.0}
	
	public static void main(String[] args) {
		String str = "";    
		double a, b;
		a = 999;
		b = 777;
		for(int i = 31; i < 41; i++){
			str += "<entity name='SoundSource"+i+"' class='ptolemy.domains.wireless.kernel.WirelessComposite'>";
	        str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[60.0, 475.0]'>";
	        str += "</property>";
	        str += "<property name='_hideName' class='ptolemy.kernel.util.Attribute'>";
	        str += "</property>";
	        str += "<property name='_icon' class='ptolemy.vergil.icon.EditorIcon'>";
	            str += "<property name='circle1' class='ptolemy.vergil.kernel.attributes.EllipseAttribute'>";
	                str += "<property name='lineWidth' class='ptolemy.data.expr.Parameter' value='1.0'>";
	                str += "</property>";
	                str += "<property name='lineColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.5, 0.5, 1.0}'>";
	                str += "</property>";
	                str += "<property name='width' class='ptolemy.data.expr.Parameter' value='20'>";
	                str += "</property>";
	                str += "<property name='height' class='ptolemy.data.expr.Parameter' value='20'>";
	                str += "</property>";
	                str += "<property name='centered' class='ptolemy.data.expr.Parameter' value='true'>";
	                str += "</property>";
	                str += "<property name='fillColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.5, 0.0, 0.0}'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='circle2' class='ptolemy.vergil.kernel.attributes.EllipseAttribute'>";
	                str += "<property name='lineWidth' class='ptolemy.data.expr.Parameter' value='1.0'>";
	                str += "</property>";
	                str += "<property name='lineColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.0, 0.0, 1.0}'>";
	                str += "</property>";
	                str += "<property name='width' class='ptolemy.data.expr.Parameter' value='40'>";
	                str += "</property>";
	                str += "<property name='height' class='ptolemy.data.expr.Parameter' value='40'>";
	                str += "</property>";
	                str += "<property name='centered' class='ptolemy.data.expr.Parameter' value='true'>";
	                str += "</property>";
	                str += "<property name='fillColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.5, 0.0, 0.0}'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='circle3' class='ptolemy.vergil.kernel.attributes.EllipseAttribute'>";
	                str += "<property name='lineWidth' class='ptolemy.data.expr.Parameter' value='1.0'>";
	                str += "</property>";
	                str += "<property name='lineColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.0, 0.0, 1.0}'>";
	                str += "</property>";
	                str += "<property name='width' class='ptolemy.data.expr.Parameter' value='60'>";
	                str += "</property>";
	                str += "<property name='height' class='ptolemy.data.expr.Parameter' value='60'>";
	                str += "</property>";
	                str += "<property name='centered' class='ptolemy.data.expr.Parameter' value='true'>";
	                str += "</property>";
	                str += "<property name='fillColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.5, 0.0, 0.0}'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='circle4' class='ptolemy.vergil.kernel.attributes.EllipseAttribute'>";
	                str += "<property name='lineWidth' class='ptolemy.data.expr.Parameter' value='1.0'>";
	                str += "</property>";
	                str += "<property name='lineColor' class='ptolemy.actor.gui.ColorAttribute' value='{0.0, 0.0, 0.0, 1.0}'>";
	                str += "</property>";
	                str += "<property name='width' class='ptolemy.data.expr.Parameter' value='soundRange*2'>";
	                str += "</property>";
	                str += "<property name='height' class='ptolemy.data.expr.Parameter' value='soundRange*2'>";
	                str += "</property>";
	                str += "<property name='centered' class='ptolemy.data.expr.Parameter' value='true'>";
	                str += "</property>";
	                str += "<property name='fillColor' class='ptolemy.actor.gui.ColorAttribute' value='none'>";
	                str += "</property>";
	            str += "</property>";
	        str += "</property>";
	        str += "<property name='soundRange' class='ptolemy.data.expr.Parameter' value='100'>";
	            str += "<property name='_hideName' class='ptolemy.kernel.util.SingletonAttribute'>";
	            str += "</property>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.ValueIcon'>";
	            str += "</property>";
	            str += "<property name='_smallIconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	            str += "<configure>";
	            str += "<svg>";
	            str += "<text x='20' style='font-size:14; font-family:SansSerif; fill:blue' y='20'>;-P-</text>";
	            str += "</svg>";
	            str += "</configure>";
	            str += "</property>";
	            str += "<property name='_editorFactory' class='ptolemy.vergil.toolbox.VisibleParameterEditorFactory'>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='175.0, 35.0'>";
	            str += "</property>";
	        str += "</property>";
	        str += "<property name='annotation' class='ptolemy.kernel.util.Attribute'>";
	            str += "<property name='_hideName' class='ptolemy.kernel.util.SingletonAttribute'>";
	            str += "</property>";
	            str += "<property name='_iconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	            str += "<configure><svg><text x='20' y='20' style='font-size:14; font-family:SansSerif; fill:blue'>Every two seconds, send a sound.</text></svg></configure>";
	            str += "</property>";
	            str += "<property name='_smallIconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	            str += "<configure>";
	            str += "<svg>";
	            str += "<text x='20' style='font-size:14; font-family:SansSerif; fill:blue' y='20'>-A-</text>";
	            str += "</svg>";
	            str += "</configure>";
	            str += "</property>";
	            str += "<property name='_controllerFactory' class='ptolemy.vergil.basic.NodeControllerFactory'>";
	            str += "</property>";
	            str += "<property name='_editorFactory' class='ptolemy.vergil.toolbox.AnnotationEditorFactory'>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='5.0, 65.0'>";
	            str += "</property>";
	        str += "</property>";
	        str += "<property name='annotation2' class='ptolemy.kernel.util.Attribute'>";
	            str += "<property name='_hideName' class='ptolemy.kernel.util.SingletonAttribute'>";
	            str += "</property>";
	            str += "<property name='_iconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	            str += "<configure><svg><text x='20' y='20' style='font-size:14; font-family:SansSerif; fill:blue'>Every second, move the sound source.</text></svg></configure>";
	            str += "</property>";
	            str += "<property name='_smallIconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	            str += "<configure>";
	            str += "<svg>";
	            str += "<text x='20' style='font-size:14; font-family:SansSerif; fill:blue' y='20'>-A-</text>";
	            str += "</svg>";
	            str += "</configure>";
	            str += "</property>";
	            str += "<property name='_controllerFactory' class='ptolemy.vergil.basic.NodeControllerFactory'>";
	            str += "</property>";
	            str += "<property name='_editorFactory' class='ptolemy.vergil.toolbox.AnnotationEditorFactory'>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='5.0, 175.0'>";
	            str += "</property>";
	        str += "</property>";
	        str += "<property name='_windowProperties' class='ptolemy.actor.gui.WindowPropertiesAttribute' value='{bounds={356, 127, 920, 545}, maximized=false}'>";
	        str += "</property>";
	        str += "<property name='_vergilSize' class='ptolemy.actor.gui.SizeAttribute' value='[697, 429]'>";
	        str += "</property>";
	        str += "<property name='_location' class='ptolemy.kernel.util.Location' value='{"+a+","+b+"}'>";
	        str += "</property>";
	        str += "<property name='_vergilZoomFactor' class='ptolemy.data.expr.ExpertParameter' value='0.9988358556461'>";
	        str += "</property>";
	        str += "<property name='_vergilCenter' class='ptolemy.data.expr.ExpertParameter' value='{363.9061771561771, 168.75}'>";
	        str += "</property>";
	        str += "<property name='idPeople' class='ptolemy.data.expr.Parameter' value='"+i+"'>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.ValueIcon'>";
	            str += "</property>";
	            str += "<property name='_smallIconDescription' class='ptolemy.kernel.util.SingletonConfigurableAttribute'>";
	                str += "<configure>";
				      str += "<svg>";
				        str += "<text x='20' style='font-size:14; font-family:SansSerif; fill:blue' y='20'>-P-</text>";
				      str += "</svg>";
				    str += "</configure>";
	            str += "</property>";
	            str += "<property name='_editorFactory' class='ptolemy.vergil.toolbox.VisibleParameterEditorFactory'>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[175.0, 0.0]'>";
	            str += "</property>";
	        str += "</property>";
	        str += "<property name='speed' class='ptolemy.data.expr.Parameter' value='10'>";
	        str += "</property>";
	        str += "<property name='movimentType' class='ptolemy.data.expr.Parameter' value='&quot;retilineo&quot;'>";
	        str += "</property>";
	        str += "<property name='xTarget' class='ptolemy.data.expr.Parameter' value='xValue'>";
	        str += "</property>";
	        str += "<property name='yTarget' class='ptolemy.data.expr.Parameter' value='yValue'>";
	        str += "</property>";
	        str += "<property name='DE Director' class='ptolemy.domains.de.kernel.DEDirector'>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[90.0, 15.0]'>";
	            str += "</property>";
	        str += "</property>";
	        
	        if(i % 10 != 0){
	        	str += "<property name='clock' class='ptolemy.data.expr.Parameter' value='1."+i+"'>";
	        }else{
	        	str += "<property name='clock' class='ptolemy.data.expr.Parameter' value='1."+i+"11'>";
	        }
	        
	            str += "<property name='_editorFactory' class='ptolemy.vergil.toolbox.VisibleParameterEditorFactory'>";
	            str += "</property>";
	        str += "</property>";
	        str += "<port name='soundOPort' class='ptolemy.domains.wireless.kernel.WirelessIOPort'>";
	            str += "<property name='output'/>";
	            str += "<property name='outsideChannel' class='ptolemy.data.expr.StringParameter' value='SoundChannel'>";
	            str += "</property>";
	            str += "<property name='outsideTransmitProperties' class='ptolemy.data.expr.Parameter' value='{range=soundRange}'>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[270.0, 140.0]'>";
	            str += "</property>";
	            str += "<property name='_hide' class='ptolemy.kernel.util.Attribute'>";
	            str += "</property>";
	        str += "</port>";
	        str += "<entity name='Clock' class='ptolemy.actor.lib.Clock'>";
	            str += "<property name='period' class='ptolemy.actor.parameters.PortParameter' value='clock'>";
	            str += "</property>";
	            str += "<property name='offsets' class='ptolemy.data.expr.Parameter' value='{0.0}'>";
	            str += "</property>";
	            str += "<property name='values' class='ptolemy.data.expr.Parameter' value='{1}'>";
	            str += "</property>";
	            str += "<property name='numberOfCycles' class='ptolemy.data.expr.Parameter' value='-1'>";
	            str += "</property>";
	            str += "<doc>Create a set of pulses</doc>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[55.0, 140.0]'>";
	            str += "</property>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.XMLIcon'>";
	            str += "</property>";
	        str += "</entity>";
	        str += "<entity name='Clock2' class='ptolemy.actor.lib.Clock'>";
	            str += "<property name='period' class='ptolemy.actor.parameters.PortParameter' value='clock'>";
	            str += "</property>";
	            str += "<property name='offsets' class='ptolemy.data.expr.Parameter' value='{0.0}'>";
	            str += "</property>";
	            str += "<property name='values' class='ptolemy.data.expr.Parameter' value='{1.0}'>";
	            str += "</property>";
	            str += "<property name='numberOfCycles' class='ptolemy.data.expr.Parameter' value='-1'>";
	            str += "</property>";
	            str += "<doc>Create a set of pulses</doc>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[55.0, 245.0]'>";
	            str += "</property>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.XMLIcon'>";
	            str += "</property>";
	        str += "</entity>";
	        str += "<entity name='SetVariable' class='ptolemy.actor.lib.SetVariable'>";
	            str += "<property name='variableName' class='ptolemy.kernel.util.StringAttribute' value='_location'>";
	            str += "</property>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.BoxedValueIcon'>";
	                str += "<property name='attributeName' class='ptolemy.kernel.util.StringAttribute' value='variableName'>";
	                str += "</property>";
	                str += "<property name='displayWidth' class='ptolemy.data.expr.Parameter' value='40'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='{475.0, 245.0}'>";
	            str += "</property>";
	        str += "</entity>";
	        str += "<entity name='Const' class='ptolemy.actor.lib.Const'>";
	            str += "<property name='value' class='ptolemy.data.expr.Parameter' value='idPeople'>";
	            str += "</property>";
	            str += "<doc>Create a constant sequence.</doc>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.BoxedValueIcon'>";
	                str += "<property name='attributeName' class='ptolemy.kernel.util.StringAttribute' value='value'>";
	                str += "</property>";
	                str += "<property name='displayWidth' class='ptolemy.data.expr.Parameter' value='60'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[175.0, 140.0]'>";
	            str += "</property>";
	        str += "</entity>";
	        str += "<entity name='MovimentoPessoa' class='ptolemy.myactors.MovimentoDePessoas.PersonWay'>";
	            str += "<property name='expression' class='ptolemy.kernel.util.StringAttribute' value='["+a+","+b+"]'>";
	            str += "</property>";
	            str += "<property name='_icon' class='ptolemy.vergil.icon.BoxedValueIcon'>";
	                str += "<property name='attributeName' class='ptolemy.kernel.util.StringAttribute' value='expression'>";
	                str += "</property>";
	                str += "<property name='displayWidth' class='ptolemy.data.expr.Parameter' value='60'>";
	                str += "</property>";
	            str += "</property>";
	            str += "<property name='_location' class='ptolemy.kernel.util.Location' value='[215.0, 245.0]'>";
	            str += "</property>";
	            str += "<property name='speed' class='ptolemy.data.expr.Parameter' value='speed'>";
	            str += "</property>";
	            str += "<property name='movimentType' class='ptolemy.data.expr.Parameter' value='movimentType'>";
	            str += "</property>";
	            str += "<property name='xTarget' class='ptolemy.data.expr.Parameter' value='xTarget'>";
	            str += "</property>";
	            str += "<property name='yTarget' class='ptolemy.data.expr.Parameter' value='yTarget'>";
	            str += "</property>";
	            str += "<port name='x' class='ptolemy.actor.TypedIOPort'>";
	                str += "<property name='input'/>";
	            str += "</port>";
	        str += "</entity>";
	        str += "<relation name='relation5' class='ptolemy.actor.TypedIORelation'>";
	            str += "<vertex name='vertex1' value='[125.0, 245.0]'>";
	            str += "</vertex>";
	        str += "</relation>";
	        str += "<relation name='relation2' class='ptolemy.actor.TypedIORelation'>";
	            str += "<property name='width' class='ptolemy.data.expr.Parameter' value='1'>";
	            str += "</property>";
	        str += "</relation>";
	        str += "<relation name='relation' class='ptolemy.actor.TypedIORelation'>";
	            str += "<property name='width' class='ptolemy.data.expr.Parameter' value='1'>";
	            str += "</property>";
	        str += "</relation>";
	        str += "<relation name='relation10' class='ptolemy.actor.TypedIORelation'>";
	            str += "<property name='width' class='ptolemy.data.expr.Parameter' value='1'>";
	            str += "</property>";
	            str += "<vertex name='vertex1' value='[355.0, 245.0]'>";
	            str += "</vertex>";
	        str += "</relation>";
	        str += "<link port='soundOPort' relation='relation'/>";
	        str += "<link port='Clock.output' relation='relation2'/>";
	        str += "<link port='Clock2.output' relation='relation5'/>";
	        str += "<link port='SetVariable.input' relation='relation10'/>";
	        str += "<link port='Const.output' relation='relation'/>";
	        str += "<link port='Const.trigger' relation='relation2'/>";
	        str += "<link port='MovimentoPessoa.output' relation='relation10'/>";
	        str += "<link port='MovimentoPessoa.x' relation='relation5'/>";
	    str += "</entity>";
		}
		System.out.println(str);
	}
}
